<a href="https://colab.research.google.com/github/azarcoder/gcollab/blob/main/numpy_aerowave.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


#range
a = np.arange(1,101)
print(a)

#single
k = np.array([1,2,3])
print(k)

#multidimentional
k = np.array([[1,2,3], [4,7,8], [2,6,7]])
print(k)

#type
print(k.dtype)

#shape
print(k.shape)

#size
print(k.size)

#dimention
print(k.ndim)

#fill value
z = np.zeros((2,3),dtype=int)
print(z)

#fill 1
o = np.ones((3,3), dtype=int)
print(o)

#linespace
l = np.linspace(0,1,20)
print(l)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[1 2 3]
[[1 2 3]
 [4 7 8]
 [2 6 7]]
int64
(3, 3)
9
2
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
import numpy as np
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

a = np.array([1,2,3,4,5,6,7,3,7])

#reshape
r = a.reshape(3,3)
print(r)

#flatten - create new copy in memory
f = r.flatten()
print(f)

#ravel (both as same as flatten) - not create a  copy in memory
#just showing like a flatten but having same memory
r = f.ravel()
r[0] = 101
print(r)
print(f) #r is a ravel of f so same memory so if r changes f also chnages

#generate random number
ar = gen(pcg())
print(ar.normal(size=(5,5))) #normal distrubution

#specific values
#seed means if we give a number, it will give same random number again otherwise give based on time
ar = gen(pcg(seed=10))
print(ar.integers(low = 10, high = 100, size=(5,5)))

[[1 2 3]
 [4 5 6]
 [7 3 7]]
[1 2 3 4 5 6 7 3 7]
[101   2   3   4   5   6   7   3   7]
[101   2   3   4   5   6   7   3   7]
[[ 0.6167348  -1.10809126 -1.54570546  0.27126797 -0.87291498]
 [-1.76977532  0.99993191 -0.40766078  2.04848541 -0.87789522]
 [ 0.30634869  0.17318928  0.3810028   0.61159554  0.71426954]
 [-0.37638955  0.99622247 -0.28613847  1.5632071  -2.29899615]
 [ 0.15259605  0.17748031  0.31594288 -1.04669712 -0.87193475]]
[[79 96 33 28 81]
 [84 56 23 84 56]
 [23 22 46 72 46]
 [85 10 48 57 96]
 [31 84 16 40 77]]


In [ ]:

#import numpy as np

a = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(a)

#indexing same as python
#negative indexing working
#but in numpy
print(a[0,0])
a[1] = 7  #put all row as 7
print(a)
'''
[[1 2 3]
 [7 7 7]]
'''

#slicing same as python
print(a[0][0:2])

print(a[0:2, 1:]) #rows 0, 1 and colum 1 and 2

print(a[:, 1]) #all row and column 1

print(a[::2, ::2]) #every 2nd row and 2nd column

x = np.arange(1,21)
print(x[2:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[[1 2 3]
 [7 7 7]
 [7 8 9]]
[1 2]
[[2 3]
 [7 7]]
[2 7 8]
[[1 3]
 [7 9]]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#brodcasting
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a+4) #4 means [4,4,4]

m = np.array([[2],[4],[6]])
print(a+m )

#concate
print(np.concatenate((a,b)))


#typeconverstion
x = np.array([0, 0, 1])
na = x.astype(bool)
print(na)

#copy - call by value (not og)
#view - call by reference (og)

#reshape
k = [1,2,3,4,5,6,7,8,9]
k = np.array(k)
print(k.reshape(3,3)) #return og

#Pass -1 as the value, and NumPy will calculate this number for you.
print(k.reshape(3,3,-1))

#flatten
print(k.reshape(-1))

#loop
for i in k:
  print(i)


[5 7 9]
[5 6 7]
[[3 4 5]
 [5 6 7]
 [7 8 9]]
[1 2 3 4 5 6]
[False False  True]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9


In [ ]:
#join

